config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  devise_for :users

  resources :users do
      resources :services
      resources :posts
      resources :contacts
      resources :profiles
  end

  resources :profiles, except: [:show ] do
    resources :contacts, only: [:index]
  end

  resources :contacts, except: [:show ] do
    resources :directions, only: [:index, :edit, :delete]
  end
  resources :posts, except: [:show ]
  resources :services, except: [:show ]
  resources :directions, only: [:edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  mount_uploader :picture, ProfilePhotoUploader

  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true

end

app/models/direction.rb
class Direction < ApplicationRecord

end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :picture, PostPictureUploader
  mount_uploader :video, VideoUploader

  validates :body, presence: true

end

app/models/profile.rb
class Profile < ApplicationRecord

end

app/models/service.rb
class Service < ApplicationRecord

  validates :name, presence: true
  validates :price, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
    @directions = Direction.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "New Contact Added!"
      redirect_to contacts_path
    else
      flash[:alert] = "New Contact Not Created"
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
   @contact = Contact.find(params[:id])
   if @contact.update_attributes(contact_params)
     flash[:notice] = "Contact Updated!"
     redirect_to contacts_path
   else
     render 'edit'
   end
 end

 def destroy
    @contact = Contact.find(params[:id])
    if @contact.destroy
      flash[:notice] = 'Contact has been deleted.'
      redirect_to contacts_path
    end
  end

  private

  def contact_params
    params.require(:contact).permit(
      :name,
      :address,
      :city,
      :zip,
      :phone,
      :email,
      :bio,
      :facebook,
      :instagram,
      :snapcht,
      :extra_one,
      :extra_two,
      :picture
    )
  end

end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

  def new
    @direction = Direction.new
  end

  def create
    @direction = Direction.new(direction_params)
    if @direction.save
      flash[:notice] = "New direction Added!"
      redirect_to contacts_path
    else
      flash[:alert] = "New direction Not Created"
      render :new
    end
  end

  def edit
    @direction = Direction.find(params[:id])
  end

  def update
   @direction = Direction.find(params[:id])
   if @direction.update_attributes(direction_params)
     flash[:notice] = "direction Updated!"
     redirect_to contacts_path
   else
     render 'edit'
   end
 end

 def destroy
    @direction = Direction.find(params[:id])
    if @direction.destroy
      flash[:notice] = 'direction has been deleted.'
      redirect_to contacts_path
    end
  end

  private

  def direction_params
    params.require(:direction).permit(
      :starting_location,
      :step_one,
      :step_two,
      :step_three,
      :step_four,
      :step_five,
      :step_six,
    )
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "New Post Added!"
      redirect_to posts_path
    else
      flash[:alert] = "New Post Not Created"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
   @post = Post.find(params[:id])
   if @post.update_attributes(post_params)
     flash[:notice] = "Post Updated!"
     redirect_to posts_path
   else
     render 'edit'
   end
 end

 def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Post has been deleted.'
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :body,
      :picture,
      :video,
      :media_type
    )
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
    @contacts = Contact.all
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
   @contact = Contact.find(params[:id])
   if @contact.update_attributes(contact_params)
     flash[:notice] = "Contact Updated!"
     redirect_to profiles_path
   else
     render 'edit'
   end
 end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      flash[:notice] = "New Service Added!"
      redirect_to services_path
    else
      flash[:alert] = "New Service Not Created"
      render :new
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
   @service = Service.find(params[:id])
   if @service.update_attributes(service_params)
     flash[:notice] = "Service Updated!"
     redirect_to services_path
   else
     render 'edit'
   end
 end

 def destroy
    @service = Service.find(params[:id])
    if @service.destroy
      flash[:notice] = 'Service has been deleted.'
      redirect_to services_path
    end
  end

  private

  def service_params
    params.require(:service).permit(
      :name,
      :price,
      :description,
      :time,
      :catagory
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :encrypted_password
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<div class="page_content">
  <%= form_for @contact do |f| %>
    <% if @contact.errors.any? %>
      <div>
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='page_content'>
      <div class="row">
        <h1 class="form_header">Update Contact Info</h1>
      </div>
      <div class="row">
        <%= f.label :address, 'Address', class: 'form-actions' %>
        <%= f.text_field :address, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :city, 'City/State', class: 'form-actions' %>
        <%= f.text_field :city, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :zip, 'Zip', class: 'form-actions' %>
        <%= f.text_field :zip, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :phone, 'Phone', class: 'form-actions' %>
        <%= f.text_field :phone, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :email, 'Email', class: 'form-actions' %>
        <%= f.text_field :email, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :facebook, 'Facebook', class: 'form-actions' %>
        <%= f.text_field :city, class: 'text_field' %>
      </div>
      <div class='page_content'>
        <div class="row">
          <h1 class="form_header">Update Profile</h1>
        </div>
        <div class="row">
          <%= f.label :picture, 'Picture', class: 'form-actions' %>
          <%= f.file_field :picture %>
        </div>
        <div class="row">
          <%= f.label :bio, 'Bio', class: 'form-actions' %>
          <%= f.text_area :bio, class: 'text_area' %>
        </div>
      <div class="form-actions">
        <%= f.button 'Update' %>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="page_header">
  <h1>Contact</h1>
</div>
<div class="page_content">
  <div class="map">
    <%= image_tag 'static-pictures/map.png', {class: 'map-pic'} %>
  </div>
  <% @contacts.each do |c| %>
    <% if user_signed_in? %>
      <%= link_to edit_contact_path(c.id) do %>
        <i class="far fa-edit fa-2x"></i>
      <% end %>
    <% end %>
    <h3><%= c.address %>, <%= c.city %> <%= c.zip %> </h3>
    <h3>Phone: <%= c.phone %></h3>
    <h3>Email: <%= c.email %></h3>
    <%= link_to c.facebook do %>
      <i class="fab fa-facebook fa"></i>
    <% end %>
    <%= link_to c.instagram do %>
      <i class="fab fa-instagram fa"></i>
    <% end %>
  <% end %>
  <br>
  <h2>Driving Directions</h2>
  <% @directions.each do |d| %>
    <button class="accordion"><%= d.starting_location %></button>
    <% if user_signed_in? %>
      <%= link_to edit_direction_path(d.id) do  %>
        <i class="far fa-edit fa-2x"></i>
      <% end %>
      <%= link_to contacts_path, data: { confirm: "Are you sure?" }, method: :delete do %>
        <i class="far fa-trash-alt fa-2x"></i>
      <% end %>
    <% end %>
    <div class="panel">
      <p><%= d.step_one %></p>
      <p><%= d.step_two %></p>
      <p><%= d.step_three %></p>
      <p><%= d.step_four %></p>
      <p><%= d.step_five %></p>
      <p><%= d.step_six %></p>
    </div>
  <% end %>
</div>


  <script type="text/javascript">
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        /* Toggle between adding and removing the "active" class,
        to highlight the button that controls the panel */
        this.classList.toggle("active");

        /* Toggle between hiding and showing the active panel */
        var panel = this.nextElementSibling;
        if (panel.style.display === "block") {
          panel.style.display = "none";
        } else {
          panel.style.display = "block";
        }
      });
    }
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <viewport>
    <title>Blush Esthetics Studio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/fe581ab890.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <div class="nav_back">
        <nav class="navbar has-background-warning" role="navigation" aria-label="main navigation">
          <div class="spacer1">

          </div>
          <div class="navbar-brand center">
           <a class="navbar-item is-size-3 is-family-secondary">
              Blush Esthetics Studio
           </a>
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
          <div class="spacer2">

          </div>
          <div id="navbarBasicExample" class="navbar-menu has-text-centered">
            <div class="navbar-start center is-size-4 is-family-secondary is-size-7-mobile">
                <%= link_to "Home", new_user_path, :class=>"navbar-item" %>
                <%= link_to "About", profiles_path, :class=>"navbar-item" %>
                <%= link_to "Services", services_path, :class=>"navbar-item" %>
                <%= link_to "Blog", posts_path, :class=>"navbar-item" %>
                <%= link_to "Contact", contacts_path, :class=>"navbar-item" %>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, {method: :delete} do %>
          <i class="fas fa-cat"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fas fa-cat"></i>
        <% end %>
      <% end %>
    </footer>
  </body>
</html>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>

app/views/posts/edit.html.erb
<div class="page_content">
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div>
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='page_content'>
      <div class="row">
        <h1 class="form_header">Update Post</h1>
      </div>
      <div class="row">
        <%= f.label :picture, 'Picture', class: 'form-actions' %>
        <%= f.file_field :picture, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :video, 'Video', class: 'form-actions' %>
        <%= f.file_field :video, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :media_type, 'Media Type', class: 'form-actions' %>
        <%= f.select :media_type, options_for_select([['Text Only', 'none'], ['Video', 'video'], ['Picture', 'picture']]) %>
      </div>
      <div class="row">
        <%= f.label :body, 'Body', class: 'form-actions' %>
        <%= f.text_area :body, class: 'text_area' %>
      </div>
      <div class="form-actions">
        <%= f.button 'Update' %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="page_header">
  <div class="title has-text-warning">
    <h1>Melissa's Blog</h1>
  </div>
</div>

<div class="container">
  <% if user_signed_in? %>
    <h2><%= link_to 'Add New Post', new_post_path %></h2>
  <% end %>
  <%  @posts.each do |p| %>
    <div class="card">
      <div class="card-image">
        <br>
        <% if p.media_type == 'picture' %>
          <div class="center_pic">
            <figure class="image">
              <%= image_tag(p.picture.url) %>
            </figure>
          </div>
        <% elsif p.media_type == 'video' %>
          <div class="center_video">
              <video controls width="640" height="480" src="<%= p.video %>"></video>
          </div>
        <% end %>
      </div>
      <br>
      <div class="card-content">
        <div class="subtitle has-text-white">
          <%= p.body %>
          <br>
          <time><%= p.created_at.strftime("%B %d, %Y") %></time>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to edit_post_path(p.id) do  %>
        <i class="far fa-edit fa-2x"></i>
      <% end %>
      <%= link_to post_path(p.id), data: { confirm: "Are you sure?" }, method: :delete do %>
        <i class="far fa-trash-alt fa-2x"></i>
      <% end %>
    <% end %>
    <br>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class='page_header'>
  <h1 class="form_header">Add a new Post</h1>
</div>
<div class="page_content">
  <%= form_for @post do |f| %>
    <div class="row">
      <%= f.label :picture, 'Picture', class: 'form-actions' %>
      <%= f.file_field :picture, class: 'text_field' %>
    </div>
    <div class="row">
      <%= f.label :video, 'Video', class: 'form-actions' %>
      <%= f.file_field :video, class: 'text_field' %>
    </div>
    <div class="row">
      <%= f.label :media_type, 'Media Type', class: 'form-actions' %>
      <%= f.select :media_type, options_for_select([['Text Only', 'none'], ['Video', 'video'], ['Picture', 'picture']]) %>
    </div>
    <div class="row">
      <%= f.label :body, 'Body', class: 'form-actions' %>
      <%= f.text_area :body, class: 'text_area' %>
    </div>
    <div class="form-actions">
      <%= f.button 'Submit' %>
    </div>
  <% end %>
</div>

app/views/profiles/index.html.erb
<br>
<div class="page_header">
  <h1 class="title is-1 is-family-secondary">Meet Melissa</h1>
</div>
<br>
<div class="container">
  <%  @contacts.each do |c| %>
    <div class="card">
      <div class="card-image">
          <%= image_tag 'static-pictures/melissa.jpg', {class: 'picture'} %>
      </div>
      <div class="card-content">
        <div class="subtitle has-text-white">
          <h3> <%= simple_format  c.bio %></h3>
        </div>
        <% if user_signed_in? %>
          <footer class="card-footer">
            <%= link_to edit_contact_path(c.id) do %>
              <i class="far fa-edit fa-2x"></i>
            <% end %>
          </footer>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/services/edit.html.erb
<div class="page_content">
  <%= form_for @service do |f| %>
    <% if @service.errors.any? %>
      <div>
        <h2><%= pluralize(@service.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @service.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='page_content'>
      <div class="row">
        <h1 class="form_header">Update Service</h1>
      </div>
      <div class="row">
        <%= f.label :name, 'Name', class: 'form-actions' %>
        <%= f.text_field :name, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :price, 'Price', class: 'form-actions' %>
        <%= f.text_field :price, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :time, 'Time', class: 'form-actions' %>
        <%= f.text_field :time, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :description, 'Description', class: 'form-actions' %>
        <%= f.text_area :description, class: 'text_area' %>
      </div>
        <%= f.label :catagory, 'Catagory', class: 'form-actions' %>
        <%= f.select :catagory, options_for_select([['Facial', 'facial'], ['Waxing', 'waxing'], ['Makeup', 'makeup'], ['Miscellaneous', 'misc']]) %>
      </div>
      <div class="form-actions">
        <%= f.button 'Update' %>
      </div>
    </div>
  <% end %>
</div>

app/views/services/index.html.erb
<div class="page_content">
  <% if user_signed_in? %>
    <h2><%= link_to 'Add New Service', new_service_path %></h2>
  <% end %>
  <br>
  <div class="page_header">
    <h1>Facials</h1>
  </div>
  <%  @services.each do |f| %>
    <% if f.catagory == 'facial' %>
      <% if user_signed_in? %>
        <%= link_to edit_service_path(f.id) do  %>
          <i class="far fa-edit fa-2x"></i>
        <% end %>
        <%= link_to service_path(f.id), data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
      <div class="service_name">
        <h3><%= f.name %></h3>
      </div>
      <div class="grid-container">
        <h3 class="service_left"><%= f.price %></h3>
        <h3 class="service_right"><%= f.time %></h3>
      </div>
      <h3 class="service_desc"><%= f.description %></h3>
    <% end %>
  <% end %>
  <br>
  <div class="page_header">
    <h1>Waxing</h1>
  </div>
  <%  @services.each do |w| %>
    <% if w.catagory == 'waxing' %>
      <% if user_signed_in? %>
        <%= link_to edit_service_path(w.id) do  %>
          <i class="far fa-edit fa-2x"></i>
        <% end %>
        <%= link_to service_path(w.id), data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
      <div class="service_name">
        <h3><%= w.name %></h3>
      </div>
      <div class="grid-container">
        <h3 class="service_left"><%= w.price %></h3>
        <h3 class="service_right"><%= w.time %></h3>
      </div>
      <h3 class="service_desc"><%= w.description %></h3>
    <% end %>
  <% end %>
  <br>
  <div class="page_header">
    <h1>Makeup</h1>
  </div>
  <%  @services.each do |m| %>
    <% if m.catagory == 'makeup' %>
      <% if user_signed_in? %>
        <%= link_to edit_service_path(m.id) do  %>
          <i class="far fa-edit fa-2x"></i>
        <% end %>
        <%= link_to service_path(m.id), data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
      <div class="service_name">
        <h3><%= m.name %></h3>
      </div>
      <div class="grid-container">
        <h3 class="service_left"><%= m.price %></h3>
        <h3 class="service_right"><%= m.time %></h3>
      </div>
      <h3 class="service_desc"><%= m.description %></h3>
    <% end %>
  <% end %>
  <br>
  <div class="page_header">
    <h1>Miscellaneous</h1>
  </div>
  <%  @services.each do |s| %>
    <% if s.catagory == 'misc' %>
      <% if user_signed_in? %>
        <%= link_to edit_service_path(s.id) do  %>
          <i class="far fa-edit fa-2x"></i>
        <% end %>
        <%= link_to service_path(s.id), data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
      <div class="service_name">
        <h3><%= s.name %></h3>
      </div>
      <div class="grid-container">
        <h3 class="service_left"><%= s.price %></h3>
        <h3 class="service_right"><%= s.time %></h3>
      </div>
      <h3 class="service_desc"><%= s.description %></h3>
    <% end %>
  <% end %>
</div>

app/views/services/new.html.erb
<div class="page_header">
  <h1>Add a Service</h1>
</div>
<div class="page_content">
  <%= form_for @service do |f| %>
    <% if @service.errors.any? %>
      <div>
        <h2><%= pluralize(@service.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @service.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='page_content'>
      <div class="row">
        <h1 class="form_header">Update Service</h1>
      </div>
      <div class="row">
        <%= f.label :name, 'Name', class: 'form-actions' %>
        <%= f.text_field :name, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :price, 'Price', class: 'form-actions' %>
        <%= f.text_field :price, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :time, 'Time', class: 'form-actions' %>
        <%= f.text_field :time, class: 'text_field' %>
      </div>
      <div class="row">
        <%= f.label :description, 'Description', class: 'form-actions' %>
        <%= f.text_area :description, class: 'text_area' %>
      </div>
      <div class="row">
        <%= f.label :catagory, 'Catagory', class: 'form-actions' %>
        <%= f.select :catagory, options_for_select([['Facial', 'facial'], ['Waxing', 'waxing'], ['Makeup', 'makeup'], ['Miscellaneous', 'misc']]) %>
      </div>
      <div class="form-actions">
        <%= f.button 'Submit' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="front_page">
  <div class="logo">
    <%= image_tag 'static-pictures/blush_circle.jpg', {class: 'logo-pic'} %>
  </div>
</div>

app/views/users/show.html.erb
<h1>hi</h1>